### PR TITLE
Issue999-AdoptMojaloopErrorHandlingSdk

### PR DESCRIPTION
**Pull request by gibaros**
-reformat generic throw err for throw FSPIOPError
-add validation and internal server error FSPIOPError at database.js

### CODE REVIEW

**Comment by gibaros** [comment]
PR ready for review, test coverage before creating branch was already below threshold. No new lines of code added just swapped throw err and throw new Error() for mojaloop FSPIOPError.

**Comment by gibaros** [comment]
Tested from Postman sending a non-valid amountType and after setting default.json SIMPLE_ROUTING_MODE=false, validated new FSPIOPError is thrown for "Generic validation error - Unsupported amount type 'SENDJ". But still need to configure the infrastructure, possible mockserver as Postman does not sees that error and log shows: "[quotesmodel]: Error in sendErrorCallback: FSPIOPError: network error in sendErrorCallback: Failed to send HTTP request to host"

**Comment by elnyry** [comment]
> Tested from Postman sending a non-valid amountType and after setting default.json SIMPLE_ROUTING_MODE=false, validated new FSPIOPError is thrown for "Generic validation error - Unsupported amount type 'SENDJ". But still need to configure the infrastructure, possible mockserver as Postman does not sees that error and log shows: "[quotesmodel]: Error in sendErrorCallback: FSPIOPError: network error in sendErrorCallback: Failed to send HTTP request to host"

@gibaros the amount type should be **SEND**, can you please confirm there's no typo?

**Comment by gibaros** [comment]
> ING_MODE=false, validated new FSPIOPError is thrown for "Generic validation error - Unsuppor

@elnyry Correct, no typo. To test the validation and specifically one of the changes at this PR to see the newly added FSPIOPError showing that it is a validation error and specifically an Unsupported amount type, at Postman request amount type was explicitly changed to "SENDJ".

**Pull request merged**
